class HTTPLogs:
    START_REQUEST_LOG = "START SEND GET REQUEST TO: {url}"
    SUCCESSFUL_REQUEST_LOG = "REQUEST SEND SUCCESSFULLY..."
    RESPONSE_RECEIVED = "RESPONSE RECEIVED: {status_code}"
    RESPONSE_DATA = "RESPONSE JSON: {_json}"
    USD_RATE_LOG = "USD RATE: {usd_rate}"


http_logs = HTTPLogs
