class RedisLogs:
    SUCCESSFULLY_CONNECT_LOG = "CONNECT TO REDIS SUCCESSFULLY..."
    CLOSE_CONNECTION_LOG = "REDIS CONNECTION CLOSED..."
    KEYS_LOG = "KEYS: {keys}"
    GET_DATA_LOG = "REDIS DATA: {data}"
    SUCCESSFULLY_SET_LOG = "SUCCESSFULLY SET DATA TO REDIS..."
